#Предложения
## Создание нового предложения
POST http://localhost:2000/rent-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzcyMzcwMiwiZXhwIjoxNjg3ODEwMTAyfQ.ilRQz_qcmgZsp47dsHo62v9xTG_lTDmiAut8lmdWkjw
Content-Type: application/json

{
  "title": "Paris offer-5",
  "description": "long description for validation testoffer",
  "city": "Paris",
  "images": [
        "offer-image-7.jpg",
        "offer-image-6.jpg",
        "offer-image-1.jpg",
        "offer-image-2.jpg",
        "offer-image-4.jpg",
        "offer-image-8.jpg"
  ],
  "isPremium": false,
  "type": "hotel",
  "bedrooms": 5,
  "maxAdults": 3,
  "price": 48410,
  "goods": [
        "Washer",
        "Laptop"
  ],
  "latitude": 50.837557,
  "longitude": 4.351697
}

###

## Получить список предложений
GET http://localhost:2000/rent-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4
###

## Получить список премиальных предложений города
GET http://localhost:2000/rent-offers/premium?city=Paris HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4
###

## Получить всю информацию о предложении
GET http://localhost:2000/rent-offers/6498b3e5f372335d3ad3d6c3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4

###

## Обновить информацию о предложении
PATCH http://localhost:2000/rent-offers/6498a59ce38bb956a9f0e70e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzcyMzcwMiwiZXhwIjoxNjg3ODEwMTAyfQ.ilRQz_qcmgZsp47dsHo62v9xTG_lTDmiAut8lmdWkjw
Content-Type: application/json

{
  "isPremium" : false,
  "bedrooms" : 2,
  "goods" : [
    "Laptop"
  ]
}

###

## Удалить предложение
DELETE http://localhost:2000/rent-offers/6498a59ce38bb956a9f0e70e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzcyMzcwMiwiZXhwIjoxNjg3ODEwMTAyfQ.ilRQz_qcmgZsp47dsHo62v9xTG_lTDmiAut8lmdWkjw


###

##Получить список комментариев к офферу
GET http://localhost:2000/rent-offers/6498b3e5f372335d3ad3d6c3/comments HTTP/1.1

###

## Загрузка preview
POST  http://localhost:2000/rent-offers/64974b9cbc8fdadc5a227253/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTIxZTgxNGQwNTAzMWI5NGIzOGQ5ZCIsImlhdCI6MTY4NzYzNjg0MywiZXhwIjoxNjg3NzIzMjQzfQ.58iVuwbVZAXdwfo6m_aW1WV5jivW8R6tvNBPVjcWL2A
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview-image"; filename="preview.png"
Content-Type: image/png

< Q:/preview.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Получить избранные предложения пользователя
GET http://localhost:2000/rent-offers/favorites/64999ee166404b7e913db229/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4

###
