#Предложения
## Создание нового предложения
POST http://localhost:2000/rent-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4Nzg2OTI4MCwiZXhwIjoxNjg3OTU1NjgwfQ.lj_LERy81_F0zR2jPDvuBemgd62017kb6TSwtdyQYHs
Content-Type: application/json

{
  "title": "new offer with no img",
  "description": "long description for validation testoffer",
  "city": "Paris",

  "isPremium": false,
  "type": "hotel",
  "bedrooms": 5,
  "maxAdults": 3,
  "price": 48410,
  "goods": [
        "Washer",
        "Laptop"
  ],
  "latitude": 50.837557,
  "longitude": 4.351697
}

###

## Получить список предложений
GET http://localhost:5000/rent-offers HTTP/1.1
// Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4
###

## Получить список премиальных предложений города
GET http://localhost:2000/rent-offers/premium?city=Paris HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4
###

## Получить всю информацию о предложении
GET http://localhost:5000/rent-offers/649b17f810fefa4c01ec7271 HTTP/1.1
//Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4

###

## Обновить информацию о предложении
PATCH http://localhost:2000/rent-offers/6498a59ce38bb956a9f0e70e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzcyMzcwMiwiZXhwIjoxNjg3ODEwMTAyfQ.ilRQz_qcmgZsp47dsHo62v9xTG_lTDmiAut8lmdWkjw
Content-Type: application/json

{
  "isPremium" : false,
  "bedrooms" : 2,
  "goods" : [
    "Laptop"
  ]
}

###

## Удалить предложение
DELETE http://localhost:2000/rent-offers/6498a59ce38bb956a9f0e70e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzcyMzcwMiwiZXhwIjoxNjg3ODEwMTAyfQ.ilRQz_qcmgZsp47dsHo62v9xTG_lTDmiAut8lmdWkjw


###

##Получить список комментариев к офферу
GET http://localhost:5000/rent-offers/649b17f810fefa4c01ec7271/comments HTTP/1.1

###


## Получить избранные предложения пользователя
GET http://localhost:2000/rent-offers/favorites/64999ee166404b7e913db229/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4

###

## Загрузка preview для оффера
POST http://localhost:2000/rent-offers/6498af6207c98cf4951723c4/upload/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzgwNDY2OSwiZXhwIjoxNjg3ODkxMDY5fQ.MkXb_6v-rEh3Gc9VRd82qOS25VTvZpg1bD_q-MqWfPw
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="preview"; filename="preview.png"
Content-Type: image/png

< Q:/preview.png
--boundary--
###

## Загрузка images для оффера
POST http://localhost:2000/rent-offers/6498af6207c98cf4951723c4/upload/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4Nzg2OTI4MCwiZXhwIjoxNjg3OTU1NjgwfQ.lj_LERy81_F0zR2jPDvuBemgd62017kb6TSwtdyQYHs
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="1.jpg"
Content-Type: image/jpeg

< Q:/images/1.jpg

--boundary
Content-Disposition: form-data; name="images"; filename="2.jpg"
Content-Type: image/jpeg

< Q:/images/2.jpg

--boundary
Content-Disposition: form-data; name="images"; filename="3.jpg"
Content-Type: image/jpeg

< Q:/images/3.jpg

--boundary
Content-Disposition: form-data; name="images"; filename="4.jpg"
Content-Type: image/jpeg

< Q:/images/4.jpg

--boundary
Content-Disposition: form-data; name="images"; filename="5.jpg"
Content-Type: image/jpeg

< Q:/images/5.jpg

--boundary
Content-Disposition: form-data; name="images"; filename="6.jpg"
Content-Type: image/jpeg

< Q:/images/6.jpg

--boundary--
###
