# Пользователи
## Регистрация нового пользователя
POST http://localhost:2000/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "testuser-2",
  "email": "user-no-advertiser@newtest.com",
  "password": "weakpass1234",
  "status": "pro"
}
###

## Авторизовать пользователя
POST http://localhost:2000/users/auth HTTP/1.1
Content-Type: application/json

{
  "email": "testuser-1@newtest.com",
  "password": "weakpass1234"
}

###

## Запрос статуса авторизации пользователя
GET  http://localhost:2000/users/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4NzYzNzc0OSwiZXhwIjoxNjg3NzI0MTQ5fQ.XiKWTNLCLDVAi3dU2lW64Q75gai0OK2Q2sdBXTmy8N8
###

## Завершения сеанса пользователя
DELETE http://localhost:2000/users/logout HTTP/1.1
X-token: 'somesupertoken'

###

## Добавление предложения в избранное
PUT http://localhost:2000/users/64999ee166404b7e913db229/favorites/6498b3f9f372335d3ad3d6cf?isFav=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjQ5OTllZTE2NjQwNGI3ZTkxM2RiMjI5IiwiaWF0IjoxNjg3Nzg5MjgxLCJleHAiOjE2ODc4NzU2ODF9.5q2CKYDMMw9vv9n4qw5i1NbbFBoIsbm_rZQnmG8KMl4


###

## Загрузка аватара пользователем

POST  http://localhost:2000/users/64974ef5bc8fdadc5a227271/upload/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3R1c2VyLTFAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTc0ZWY1YmM4ZmRhZGM1YTIyNzI3MSIsImlhdCI6MTY4Nzg2OTI4MCwiZXhwIjoxNjg3OTU1NjgwfQ.lj_LERy81_F0zR2jPDvuBemgd62017kb6TSwtdyQYHs
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< Q:/нафиксон.jpg
--boundary--


###



